apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-service
  labels:
    app: friend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend-service
  template:
    metadata:
      labels:
        app: friend-service
    spec:
      containers:
        - name: friend-service
          image: docker.io/vtri/friend-service
          ports:
            - containerPort: 5000
          # imagePullPolicy: Always
