apiVersion: apps/v1
kind: Deployment
metadata:
  name: noti-service
  labels:
    app: noti-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noti-service
  template:
    metadata:
      labels:
        app: noti-service
    spec:
      containers:
        - name: noti-service
          image: docker.io/vtri/noti-service
          ports:
            - containerPort: 5000
          # imagePullPolicy: Always
